### PR TITLE
Switch logging to stdout rather than stderr

### PR DESCRIPTION
**Pull request by WhiteHalmos**
Makes it easier to have cron jobs save all logging to a file via stdout
and still issue an email if an exception occurs outside of logging.

### CODE REVIEW

**Comment by WhiteHalmos** [comment]
Does this break any of your scripts or workflows?

**Comment by robert-wallis** [comment]
It doesn’t break anything for me.  If there is an error and the exit code is non-zero then I can look at stdout for the error.  But if it exits 0 and puts errors in stdout then it will be harder.

**Comment by WhiteHalmos** [comment]
> It doesn’t break anything for me. If there is an error and the exit code is non-zero then I can look at stdout for the error. But if it exits 0 and puts errors in stdout then it will be harder.

From my experience this only changes output to stdout for strings that are sent through the logging API. Top level python exceptions still get sent to stderr and should still exit with nonzero.

**Comment by WhiteHalmos** [comment]
Primary use case is in crontab, doing:

* * * * * email >> log_file

Allows all logging to be captured, but still send an email if there are real exceptions that caused the emailer to fail.

**Comment by WhiteHalmos** [comment]
Thought about it a bit more, won't work with outputting markdown.

**Comment by WhiteHalmos** [comment]
I'll find another way to run my cron jobs, likely just without `-v`. The emailer should output nothing when running without `-v` and exit code of 0 (apart from version checks and such).

**Pull request closed without merging**
